
projectid: us-gcp-ame-its-23a8a-sbx-1
namespace: product-ns
projectRef: projects/us-gcp-ame-its-23a8a-sbx-1


GKEHubFeature:
  name: configmanagement
  location: global
  resourceID: configmanagement

GKEHubFeatureMembership:

  location: global
  name: a-featuremembership
  membershipRef: projects/us-gcp-ame-its-23a8a-sbx-1/locations/global/memberships/a-membership
  featureRef: projects/us-gcp-ame-its-23a8a-sbx-1/locations/global/features/configmanagement

  sourceFormat: unstructured
  git:
    syncRepo: "https://github.com/GoogleCloudPlatform/microservices-demo.git"
    syncBranch: "main"
    policyDir: "./release"
    syncWaitSecs: "20"
    syncRev: "HEAD"
    secretType: "none"
  policyController:
    enabled: true
    referentialRulesEnabled: true
    logDeniesEnabled: true
    templateLibraryInstalled: true
    auditIntervalSeconds: "20"
  binauthz: true
  hierarchyController:
    enabled: true
    enablePodTreeLabels: true
    enableHierarchicalResourceQuota: true

GKEHubMembership:

  name: a-membership
  location: global
  authorityissuer: https://container.googleapis.com/v1/projects/us-gcp-ame-its-23a8a-sbx-1/locations/us-west1/clusters/a-final-app-1
  gkeCluster: https://container.googleapis.com/v1beta1/projects/us-gcp-ame-its-23a8a-sbx-1/locations/us-west1/clusters/a-final-app-1
