projectname: us-gcp-ame-its-23a8a-sbx-1

Namespace:
  name: product-ns

ContainerNodePool:
  name: a-final-app-nodepool
  location: us-west1
  autoscalingmin: 5
  autoscalingmax: 6
  nodeConfig:
    machineType: n1-standard-1
    diskSizeGb: 100
    diskType: pd-standard
    preemptible: false
    minCpuPlatform: Intel Haswell
    disablelegacyendpoints: true
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: a-final-app

ContainerCluster:
  name: a-final-app-3
  location: us-west1
  initialNodeCount: 3
  workloadIdentityConfig:
    workloadPool: us-gcp-ame-its-23a8a-sbx-1.svc.id.goog
  configConnectorConfigenabled: true
  networkRef: a-dep-network
  subnetworkRef: a-dep-network
  serviceAccountRef: tf-gke-anthos-product--zr38@us-gcp-ame-its-23a8a-sbx-1.iam.gserviceaccount.com

